/**
 * Centralized configuration for DSPCLAW
 * All hard-coded values are collected here for easy maintenance and environment-specific overrides.
 */

// ============================================================================
// AI Provider Configuration
// ============================================================================

export interface ProviderConfig {
  apiBase: string;
  modelsEndpoint: string;
  defaultModel: string;
  defaultModels: string[];
}

export const PROVIDERS: Record<string, ProviderConfig> = {
  gemini: {
    apiBase: 'https://generativelanguage.googleapis.com/v1beta',
    modelsEndpoint: '/models', // Gemini uses x-goog-api-key header
    defaultModel: 'gemini-2.0-flash',
    defaultModels: [],
  },
  moonshot: {
    apiBase: 'https://api.moonshot.cn/v1',
    modelsEndpoint: '/models',
    defaultModel: 'kimi-2.5',
    defaultModels: ['kimi-2.5', 'moonshot-v1-32k', 'moonshot-v1-8k'],
  },
  deepseek: {
    apiBase: 'https://api.deepseek.com',
    modelsEndpoint: '/models',
    defaultModel: 'deepseek-chat',
    defaultModels: ['deepseek-chat', 'deepseek-reasoner'],
  },
  glm: {
    apiBase: 'https://open.bigmodel.cn/api/paas/v4',
    modelsEndpoint: '/models',
    defaultModel: 'glm-4.5',
    defaultModels: ['glm-4.5', 'glm-4.6', 'glm-4.7', 'glm-5', 'glm-5-turbo', 'glm-5.1'],
  },
  openai: {
    apiBase: 'https://api.openai.com/v1',
    modelsEndpoint: '/models',
    defaultModel: 'gpt-4o',
    defaultModels: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo'],
  },
};

// ============================================================================
// Faust Configuration
// ============================================================================

export const FAUST_CONFIG = {
  /** Base URL for Faust WASM files */
  wasmBaseUrl: './faustwasm/',

  /** Number of voices for polyphonic DSP */
  polyVoiceCount: 4,

  /** Sample rate (0 = use device default) */
  sampleRate: 0,
};

// ============================================================================
// Audio Configuration
// ============================================================================

export const AUDIO_CONFIG = {
  /** Default audio input volume for effects */
  defaultAudioInputVolume: 0.5,

  /** Audio context options */
  contextOptions: {
    sampleRate: FAUST_CONFIG.sampleRate || undefined,
  },
};

// ============================================================================
// MIDI Configuration
// ============================================================================

export const MIDI_CONFIG = {
  /** Computer keyboard to MIDI note mapping (QWERTY layout) */
  keyboardMapping: {
    // White keys
    'a': 60, 's': 62, 'd': 64, 'f': 65, 'g': 67, 'h': 69, 'j': 71, 'k': 72,
    'w': 61, 'e': 63, 't': 66, 'y': 68, 'u': 70,
  },
};

// ============================================================================
// Default Session Templates
// ============================================================================

export const DEFAULT_SYNTH_CODE = `// generated by DSPCLAW
import("stdfaust.lib");

freq = nentry("freq", 440, 20, 20000, 0.01);
gate = nentry("gate", 0, 0, 1, 1);
gain = nentry("gain", 0.5, 0, 1, 0.01);

osc = os.sawtooth(freq) + (os.osc(freq * 0.5) * 0.5);
cutoff = hslider("Cutoff[style:knob][scale:log]", 2000, 100, 12000, 10);
resonance = hslider("Resonance[style:knob]", 0.3, 0, 1, 0.01);
filt = fi.resonlp(cutoff, resonance, 1);

env = en.adsr(
    hslider("Attack[style:knob][scale:log]", 0.01, 0.001, 1, 0.001),
    hslider("Decay[style:knob][scale:log]", 0.3, 0.01, 1, 0.01),
    hslider("Sustain[style:knob]", 0.5, 0, 1, 0.01),
    hslider("Release[style:knob][scale:log]", 0.3, 0.01, 2, 0.01),
    gate
);

synth = osc : filt : *(env) : *(gain * 0.5);
process = synth <: _, _;`;

export const DEFAULT_EFFECT_CODE = `// generated by DSPCLAW
import("stdfaust.lib");

cutoff = hslider("Cutoff[style:knob][scale:log]", 2000, 100, 12000, 10);
resonance = hslider("Resonance[style:knob]", 0.3, 0, 1, 0.01);

process = fi.resonlp(cutoff, resonance, 1) <: _, _;`;

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get provider configuration, with fallback for custom providers
 */
export function getProviderConfig(providerId: string): ProviderConfig {
  return PROVIDERS[providerId] || {
    apiBase: PROVIDERS.openai.apiBase,
    modelsEndpoint: PROVIDERS.openai.modelsEndpoint,
    defaultModel: 'gpt-4o',
    defaultModels: ['gpt-4o'],
  };
}

/**
 * Get the API base URL for a provider
 */
export function getApiBase(providerId: string): string {
  return getProviderConfig(providerId).apiBase;
}

/**
 * Get the models endpoint for a provider
 */
export function getModelsUrl(providerId: string): string {
  const config = getProviderConfig(providerId);
  return `${config.apiBase}${config.modelsEndpoint}`;
}
