import { create } from 'zustand';
import type { FaustAudioWorkletNode, FaustScriptProcessorNode } from '@grame/faustwasm';
import { type ChatMessage } from './agent/types';
import { clearAgentCache } from './agent/agent-cache';
import { IS_ELECTRON_APP } from './utils/env';
import { getProviderConfig } from './config';

export type AIProvider = string;
export type SessionType = 'poly' | 'mono';

export interface CustomProvider {
  id: string;
  name: string;
  baseUrl: string;
}

export interface Session {
  id: string;
  name: string;
  type: SessionType;
  code: string;
  uiLayout: any[];
  dspNode: FaustAudioWorkletNode | FaustScriptProcessorNode | null;
  audioInputUrl: string;
  audioInputVolume: number;
  midiInputId: string;
  isCompiling: boolean;
  compileError: string | null;
  messages: ChatMessage[];
  isAiThinking: boolean;
  model: string;
  models: string[];
  tokenUsage?: {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
  };
}

interface AppState {
  sessions: Session[];
  activeSessionId: string;
  isAudioRunning: boolean;
  isInitialized: boolean;
  
  // Settings (Global)
  provider: AIProvider;
  apiKeys: Record<AIProvider, string>;
  customBaseUrl: string;
  customProviders: CustomProvider[];
  setSettings: (settings: { provider?: AIProvider, apiKey?: string, customBaseUrl?: string }) => void | Promise<void>;
  setApiKey: (providerId: AIProvider, apiKey: string) => Promise<void>;
  addCustomProvider: (provider: CustomProvider) => void;
  removeCustomProvider: (id: string) => void;

  // MIDI Global State
  midiDevices: { id: string, name: string }[];
  setMidiDevices: (devices: { id: string, name: string }[]) => void;
  lastMidiNote: number | null;
  setLastMidiNote: (note: number | null) => void;

  // Session Actions
  addSession: (name: string, type: SessionType) => void;
  setSessionModel: (sessionId: string, model: string) => void;
  switchSession: (id: string) => void;
  deleteSession: (id: string) => void;
  renameSession: (id: string, name: string) => void;
  updateActiveSession: (updates: Partial<Session>) => void;
  updateSession: (id: string, updates: Partial<Session>) => void;
  getActiveSession: () => Session | undefined;

  // Global Actions
  setAudioRunning: (running: boolean) => void;
  setInitialized: (initialized: boolean) => void;
  getAudioCtx: () => AudioContext;
}

let globalAudioCtx: AudioContext | null = null;

const safeLocalStorage = {
  getItem: (key: string): string | null => {
    try {
      return localStorage.getItem(key);
    } catch (e) {
      console.warn(`[DSPCLAW] Storage access blocked: ${key}`);
      return null;
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      localStorage.setItem(key, value);
    } catch (e) {
      console.warn(`[DSPCLAW] Storage write blocked: ${key}`);
    }
  },
  removeItem: (key: string): void => {
    try {
      localStorage.removeItem(key);
    } catch (e) {
      console.warn(`[DSPCLAW] Storage remove blocked: ${key}`);
    }
  }
};

const DEFAULT_SYNTH_CODE = `// generated by DSPCLAW
import("stdfaust.lib");

freq = nentry("freq", 440, 20, 20000, 0.01);
gate = nentry("gate", 0, 0, 1, 1);
gain = nentry("gain", 0.5, 0, 1, 0.01);

osc = os.sawtooth(freq) + (os.osc(freq * 0.5) * 0.5);
cutoff = hslider("Cutoff[style:knob][scale:log]", 2000, 100, 12000, 10);
resonance = hslider("Resonance[style:knob]", 0.3, 0, 1, 0.01);
filt = fi.resonlp(cutoff, resonance, 1);

env = en.adsr(
    hslider("Attack[style:knob][scale:log]", 0.01, 0.001, 1, 0.001),
    hslider("Decay[style:knob][scale:log]", 0.3, 0.01, 1, 0.01),
    hslider("Sustain[style:knob]", 0.5, 0, 1, 0.01),
    hslider("Release[style:knob][scale:log]", 0.3, 0.01, 2, 0.01),
    gate
);

synth = osc : filt : *(env) : *(gain * 0.5);
process = synth <: _, _;`;

const DEFAULT_EFFECT_CODE = `// generated by DSPCLAW
import("stdfaust.lib");

cutoff = hslider("Cutoff[style:knob][unit:Hz][scale:log]", 2000, 20, 20000, 1);
res = hslider("Resonance[style:knob]", 0.3, 0, 1, 0.01);
drive = hslider("Drive[style:knob][unit:dB]", 0, 0, 24, 0.1);
mode = hslider("Mode[style:menu{'Lowpass':0;'Highpass':1}]", 0, 0, 1, 1);

drive_amt = ba.db2linear(drive);

ms20_filter(cut, res, lp_hp, x) = lp, hp
with {
    q = 1.0 + (res * 4.0);
    driven = x * drive_amt : ma.tanh;
    lp = fi.svf.lp(cut, q, driven);
    hp = fi.svf.hp(cut, q, driven);
};

lp_out(x) = ms20_filter(cutoff, res, mode, x) : _, !;
hp_out(x) = ms20_filter(cutoff, res, mode, x) : !, _;

process = _ <: (lp_out, hp_out) : select2(mode) : *(ba.db2linear(-drive * 0.5));`;

export const useStore = create<AppState>((set, get) => {
  const initialProvider = (safeLocalStorage.getItem('faust_provider') as AIProvider) || 'moonshot';
  
  let initialCustomProviders: CustomProvider[] = [];
  try {
    const stored = safeLocalStorage.getItem('faust_custom_providers');
    if (stored) initialCustomProviders = JSON.parse(stored);
  } catch (e) {}

  // Helper to get API key from localStorage or fallback to env vars (dev only)
  const getApiKeyFromEnv = (provider: AIProvider): string => {
    const stored = safeLocalStorage.getItem(`faust_api_key_${provider}`);
    if (stored) return stored;
    // Only use env vars in development mode (not in production builds)
    if (import.meta.env.DEV) {
      const envKey = import.meta.env[`VITE_${provider.toUpperCase()}_API_KEY`];
      return envKey || '';
    }
    return '';
  };

  const initialKeys: Record<AIProvider, string> = {
    moonshot: getApiKeyFromEnv('moonshot'),
    gemini: getApiKeyFromEnv('gemini'),
    deepseek: getApiKeyFromEnv('deepseek'),
    glm: getApiKeyFromEnv('glm'),
  };

  initialCustomProviders.forEach((p: any) => {
    initialKeys[p.id] = safeLocalStorage.getItem(`faust_api_key_${p.id}`) || '';
  });

  // Only load a model if an API key exists for the provider
  let initialModel = '';
  if (initialKeys[initialProvider]) {
    const savedModel = safeLocalStorage.getItem(`faust_model_${initialProvider}`);
    initialModel = savedModel || '';
    
    // Set decent defaults if key exists but no model saved
    if (!initialModel) {
      const config = getProviderConfig(initialProvider);
      initialModel = config.defaultModel;
    }
  }

  if (IS_ELECTRON_APP) {
    (async () => {
      const providers: AIProvider[] = ['moonshot', 'gemini', 'deepseek', 'glm', ...initialCustomProviders.map(p => p.id)];
      const secureKeys = { ...initialKeys };
      let changed = false;
      for (const p of providers) {
        const encrypted = safeLocalStorage.getItem(`faust_api_key_secure_${p}`);
        if (encrypted) {
          const decrypted = await (window as any).ipcRenderer.invoke('safe-storage:decrypt', encrypted);
          if (decrypted) {
            secureKeys[p] = decrypted;
            changed = true;
          }
        }
      }
      if (changed) {
        set(() => {
          return { 
            apiKeys: secureKeys
          };
        });
      }
    })();
  }

  const initialSessions: Session[] = [
    { id: 'default-synth', name: 'CLAW Synth', type: 'poly', code: DEFAULT_SYNTH_CODE, uiLayout: [], dspNode: null, audioInputUrl: './audio/stay-a-while.mp3', audioInputVolume: 0.5, midiInputId: 'all', isCompiling: false, compileError: null, messages: [], isAiThinking: false, model: initialModel, models: [], tokenUsage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 } },
    { id: 'default-effect', name: 'CLAW Effect', type: 'mono', code: DEFAULT_EFFECT_CODE, uiLayout: [], dspNode: null, audioInputUrl: './audio/stay-a-while.mp3', audioInputVolume: 0.5, midiInputId: 'all', isCompiling: false, compileError: null, messages: [], isAiThinking: false, model: initialModel, models: [], tokenUsage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 } }
  ];

  return {
    sessions: initialSessions,
    activeSessionId: 'default-synth',
    isAudioRunning: false,
    isInitialized: false,
    midiDevices: [],
    lastMidiNote: null,

    provider: initialProvider,
    apiKeys: initialKeys,
    customBaseUrl: safeLocalStorage.getItem('faust_custom_base_url') || '',
    customProviders: initialCustomProviders,

    addCustomProvider: (provider) => set((state) => {
      const newProviders = [...state.customProviders, provider];
      safeLocalStorage.setItem('faust_custom_providers', JSON.stringify(newProviders));
      return { customProviders: newProviders, apiKeys: { ...state.apiKeys, [provider.id]: '' } };
    }),

    removeCustomProvider: (id) => set((state) => {
      const newProviders = state.customProviders.filter(p => p.id !== id);
      safeLocalStorage.setItem('faust_custom_providers', JSON.stringify(newProviders));
      
      let newProvider = state.provider;
      if (state.provider === id) {
        newProvider = 'moonshot';
        safeLocalStorage.setItem('faust_provider', newProvider);
      }
      return { customProviders: newProviders, provider: newProvider };
    }),

    addSession: (name, type) => {
      const state = get();
      const id = Math.random().toString(36).substring(7);

      // Default model for new session based on current provider
      // First try to load saved model from localStorage
      let defaultModel = safeLocalStorage.getItem(`faust_model_${state.provider}`) || '';
      if (!defaultModel) {
        const config = getProviderConfig(state.provider);
        defaultModel = config.defaultModel;
      }

      const newSession: Session = { id, name, type, code: type === 'poly' ? DEFAULT_SYNTH_CODE : DEFAULT_EFFECT_CODE, uiLayout: [], dspNode: null, audioInputUrl: './audio/stay-a-while.mp3', audioInputVolume: 0.5, midiInputId: 'all', isCompiling: false, compileError: null, messages: [], isAiThinking: false, model: defaultModel, models: [], tokenUsage: { inputTokens: 0, outputTokens: 0, totalTokens: 0 } };
      set((state) => ({ sessions: [...state.sessions, newSession], activeSessionId: id }));
    },

    setSessionModel: (sessionId, model) => set((state) => {
      // Persist model per provider
      safeLocalStorage.setItem(`faust_model_${state.provider}`, model);
      // Clear agent cache so new model takes effect
      clearAgentCache();
      return {
        sessions: state.sessions.map((s) =>
          s.id === sessionId ? { ...s, model } : s
        )
      };
    }),

    switchSession: (id) => {
      const state = get();
      const currentSession = state.getActiveSession();
      const nextSession = state.sessions.find(s => s.id === id);
      if (currentSession?.dspNode) currentSession.dspNode.disconnect();
      if (nextSession?.dspNode && state.isAudioRunning) nextSession.dspNode.connect(state.getAudioCtx().destination);
      set({ activeSessionId: id });
    },

    deleteSession: (id) => {
      set((state) => {
        const session = state.sessions.find(s => s.id === id);
        if (session?.dspNode) { session.dspNode.disconnect(); session.dspNode.destroy(); }
        const newSessions = state.sessions.filter(s => s.id !== id);
        let nextId = state.activeSessionId;
        if (id === state.activeSessionId) nextId = newSessions.length > 0 ? newSessions[0].id : '';
        return { sessions: newSessions, activeSessionId: nextId };
      });
    },

    renameSession: (id, name) => set((state) => ({ sessions: state.sessions.map((s) => s.id === id ? { ...s, name } : s) })),
    updateActiveSession: (updates) => set((state) => ({ sessions: state.sessions.map((s) => s.id === state.activeSessionId ? { ...s, ...updates } : s) })),
    updateSession: (id, updates) => set((state) => ({ sessions: state.sessions.map((s) => s.id === id ? { ...s, ...updates } : s) })),
    getActiveSession: () => { const state = get(); return state.sessions.find(s => s.id === state.activeSessionId); },

    setSettings: async (settings) => {
      const current = get();
      const newProvider = settings.provider || current.provider;
      const newApiKeys = { ...current.apiKeys };
      
      // Clear agent cache if provider or apiKey changes
      if (settings.provider || (settings.apiKey !== undefined && settings.apiKey !== current.apiKeys[newProvider])) {
        clearAgentCache();
      }

      if (settings.apiKey !== undefined) {
        // Prevent empty string from overwriting a valid key during auto-fill events
        // unless the user is explicitly deleting it.
        if (settings.apiKey === '' && current.apiKeys[newProvider] !== '') {
           // If it's just an empty string and we had a key, it might be an auto-fill clearing event
           // We only accept explicit clearing if the modal is actually open and focused
           const isSettingsInput = document.activeElement?.getAttribute('name')?.startsWith('faust-api-key-');
           if (!isSettingsInput) return; 
        }

        newApiKeys[newProvider] = settings.apiKey;
        if (IS_ELECTRON_APP) {
          const encrypted = await (window as any).ipcRenderer.invoke('safe-storage:encrypt', settings.apiKey);
          safeLocalStorage.setItem(`faust_api_key_secure_${newProvider}`, encrypted);
          safeLocalStorage.removeItem(`faust_api_key_${newProvider}`);
        } else {
          safeLocalStorage.setItem(`faust_api_key_${newProvider}`, settings.apiKey);
        }
      }

      let newSessions = current.sessions;
      if (settings.provider && settings.provider !== current.provider) {
        // Restore saved model for the new provider, or use default
        const savedModel = safeLocalStorage.getItem(`faust_model_${settings.provider}`);
        let newModel = savedModel || '';
        if (!newModel) {
          const config = getProviderConfig(settings.provider);
          newModel = config.defaultModel;
        }
        newSessions = newSessions.map(s => ({ ...s, models: [], model: newModel }));
      }

      safeLocalStorage.setItem('faust_provider', newProvider);
      set({ provider: newProvider, apiKeys: newApiKeys, customBaseUrl: settings.customBaseUrl ?? current.customBaseUrl, sessions: newSessions });
    },

    setApiKey: async (providerId, apiKey) => {
      const current = get();
      const newApiKeys = { ...current.apiKeys };

      if (apiKey === '' && current.apiKeys[providerId] !== '') {
         const isSettingsInput = document.activeElement?.getAttribute('name')?.startsWith('faust-api-key-');
         if (!isSettingsInput) return; 
      }

      newApiKeys[providerId] = apiKey;
      if (IS_ELECTRON_APP) {
        const encrypted = await (window as any).ipcRenderer.invoke('safe-storage:encrypt', apiKey);
        safeLocalStorage.setItem(`faust_api_key_secure_${providerId}`, encrypted);
        safeLocalStorage.removeItem(`faust_api_key_${providerId}`);
      } else {
        safeLocalStorage.setItem(`faust_api_key_${providerId}`, apiKey);
      }

      if (current.provider === providerId) {
        clearAgentCache();
      }

      set({ apiKeys: newApiKeys });
    },

    setAudioRunning: (running) => set({ isAudioRunning: running }),
    setInitialized: (initialized) => set({ isInitialized: initialized }),
    setMidiDevices: (midiDevices) => set({ midiDevices }),
    setLastMidiNote: (lastMidiNote) => set({ lastMidiNote }),
    getAudioCtx: () => {
      if (!globalAudioCtx) globalAudioCtx = new (window.AudioContext || (window as any).webkitAudioContext)();
      return globalAudioCtx;
    }
  };
});