import { create } from 'zustand';
import type { FaustAudioWorkletNode, FaustScriptProcessorNode } from '@grame/faustwasm';
import { type ChatMessage } from './agent/types';

export type AIProvider = 'moonshot' | 'gemini' | 'deepseek' | 'glm';
export type SessionType = 'poly' | 'mono';

export interface Session {
  id: string;
  name: string;
  type: SessionType;
  code: string;
  uiLayout: any[];
  dspNode: FaustAudioWorkletNode | FaustScriptProcessorNode | null;
  audioInputUrl: string;
  audioInputVolume: number;
  midiInputId: string;
  isCompiling: boolean;
  compileError: string | null;
  messages: ChatMessage[];
  isAiThinking: boolean;
}

interface AppState {
  sessions: Session[];
  activeSessionId: string;
  isAudioRunning: boolean;
  isInitialized: boolean;
  
  // Settings (Global)
  provider: AIProvider;
  apiKeys: Record<AIProvider, string>;
  model: string;
  customBaseUrl: string;
  models: string[];
  setSettings: (settings: { provider?: AIProvider, apiKey?: string, model?: string, customBaseUrl?: string, models?: string[] }) => void | Promise<void>;

  // MIDI Global State
  midiDevices: { id: string, name: string }[];
  setMidiDevices: (devices: { id: string, name: string }[]) => void;
  lastMidiNote: number | null;
  setLastMidiNote: (note: number | null) => void;

  // Session Actions
  addSession: (name: string, type: SessionType) => void;
  switchSession: (id: string) => void;
  deleteSession: (id: string) => void;
  renameSession: (id: string, name: string) => void;
  updateActiveSession: (updates: Partial<Session>) => void;
  updateSession: (id: string, updates: Partial<Session>) => void;
  getActiveSession: () => Session | undefined;

  // Global Actions
  setAudioRunning: (running: boolean) => void;
  setInitialized: (initialized: boolean) => void;
  getAudioCtx: () => AudioContext;
}

let globalAudioCtx: AudioContext | null = null;

const isElectron = !!(window as any).ipcRenderer;

const safeLocalStorage = {
  getItem: (key: string): string | null => {
    try {
      return localStorage.getItem(key);
    } catch (e) {
      console.warn(`[DSPCLAW] Storage access blocked: ${key}`);
      return null;
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      localStorage.setItem(key, value);
    } catch (e) {
      console.warn(`[DSPCLAW] Storage write blocked: ${key}`);
    }
  },
  removeItem: (key: string): void => {
    try {
      localStorage.removeItem(key);
    } catch (e) {
      console.warn(`[DSPCLAW] Storage remove blocked: ${key}`);
    }
  }
};

const DEFAULT_SYNTH_CODE = `// generated by DSPCLAW
import("stdfaust.lib");

freq = nentry("freq", 440, 20, 20000, 0.01);
gate = nentry("gate", 0, 0, 1, 1);
gain = nentry("gain", 0.5, 0, 1, 0.01);

osc = os.sawtooth(freq) + (os.osc(freq * 0.5) * 0.5);
cutoff = hslider("Cutoff[style:knob][scale:log]", 2000, 100, 12000, 10);
resonance = hslider("Resonance[style:knob]", 0.3, 0, 1, 0.01);
filt = fi.resonlp(cutoff, resonance, 1);

env = en.adsr(
    hslider("Attack[style:knob][scale:log]", 0.01, 0.001, 1, 0.001),
    hslider("Decay[style:knob][scale:log]", 0.3, 0.01, 1, 0.01),
    hslider("Sustain[style:knob]", 0.5, 0, 1, 0.01),
    hslider("Release[style:knob][scale:log]", 0.3, 0.01, 2, 0.01),
    gate
);

synth = osc : filt : *(env) : *(gain * 0.5);
process = synth <: _, _;`;

const DEFAULT_EFFECT_CODE = `// generated by DSPCLAW
import("stdfaust.lib");

cutoff = hslider("Cutoff[style:knob][unit:Hz][scale:log]", 2000, 20, 20000, 1);
res = hslider("Resonance[style:knob]", 0.3, 0, 1, 0.01);
drive = hslider("Drive[style:knob][unit:dB]", 0, 0, 24, 0.1);
mode = hslider("Mode[style:menu{'Lowpass':0;'Highpass':1}]", 0, 0, 1, 1);

drive_amt = ba.db2linear(drive);

ms20_filter(cut, res, lp_hp, x) = lp, hp
with {
    q = 1.0 + (res * 4.0);
    driven = x * drive_amt : ma.tanh;
    lp = fi.svf.lp(cut, q, driven);
    hp = fi.svf.hp(cut, q, driven);
};

lp_out(x) = ms20_filter(cutoff, res, mode, x) : _, !;
hp_out(x) = ms20_filter(cutoff, res, mode, x) : !, _;

process = _ <: (lp_out, hp_out) : select2(mode) : *(ba.db2linear(-drive * 0.5));`;

export const useStore = create<AppState>((set, get) => {
  const initialProvider = (safeLocalStorage.getItem('faust_provider') as AIProvider) || 'moonshot';
  const initialKeys: Record<AIProvider, string> = {
    moonshot: safeLocalStorage.getItem('faust_api_key_moonshot') || '',
    gemini: safeLocalStorage.getItem('faust_api_key_gemini') || '',
    deepseek: safeLocalStorage.getItem('faust_api_key_deepseek') || '',
    glm: safeLocalStorage.getItem('faust_api_key_glm') || '',
  };

  // Only load a model if an API key exists for the provider
  let initialModel = '';
  if (initialKeys[initialProvider]) {
    const savedModel = safeLocalStorage.getItem(`faust_model_${initialProvider}`);
    initialModel = savedModel || '';
    
    // Set decent defaults if key exists but no model saved
    if (!initialModel) {
      switch(initialProvider) {
        case 'moonshot': initialModel = 'moonshot-v1-8k'; break;
        case 'gemini': initialModel = 'gemini-1.5-flash-latest'; break;
        case 'deepseek': initialModel = 'deepseek-chat'; break;
        case 'glm': initialModel = 'glm-4'; break;
      }
    }
  }

  if (isElectron) {
    (async () => {
      const providers: AIProvider[] = ['moonshot', 'gemini', 'deepseek', 'glm'];
      const secureKeys = { ...initialKeys };
      let changed = false;
      for (const p of providers) {
        const encrypted = safeLocalStorage.getItem(`faust_api_key_secure_${p}`);
        if (encrypted) {
          const decrypted = await (window as any).ipcRenderer.invoke('safe-storage:decrypt', encrypted);
          if (decrypted) {
            secureKeys[p] = decrypted;
            changed = true;
          }
        }
      }
      if (changed) {
        set((state) => {
          const currentKey = secureKeys[state.provider];
          const currentSavedModel = safeLocalStorage.getItem(`faust_model_${state.provider}`);
          let finalModel = state.model;
          
          if (!currentKey) {
            finalModel = '';
          } else if (!finalModel && currentSavedModel) {
            finalModel = currentSavedModel;
          }
          
          return { 
            apiKeys: secureKeys, 
            model: finalModel
          };
        });
      }
    })();
  }

  const initialSessions: Session[] = [
    { id: 'default-synth', name: 'CLAW Synth', type: 'poly', code: DEFAULT_SYNTH_CODE, uiLayout: [], dspNode: null, audioInputUrl: './audio/stay-a-while.mp3', audioInputVolume: 0.5, midiInputId: 'all', isCompiling: false, compileError: null, messages: [], isAiThinking: false },
    { id: 'default-effect', name: 'CLAW Effect', type: 'mono', code: DEFAULT_EFFECT_CODE, uiLayout: [], dspNode: null, audioInputUrl: './audio/stay-a-while.mp3', audioInputVolume: 0.5, midiInputId: 'all', isCompiling: false, compileError: null, messages: [], isAiThinking: false }
  ];

  return {
    sessions: initialSessions,
    activeSessionId: 'default-synth',
    isAudioRunning: false,
    isInitialized: false,
    midiDevices: [],
    lastMidiNote: null,

    provider: initialProvider,
    apiKeys: initialKeys,
    model: initialModel,
    customBaseUrl: safeLocalStorage.getItem('faust_custom_base_url') || '',
    models: [],

    addSession: (name, type) => {
      const id = Math.random().toString(36).substring(7);
      const newSession: Session = { id, name, type, code: type === 'poly' ? DEFAULT_SYNTH_CODE : DEFAULT_EFFECT_CODE, uiLayout: [], dspNode: null, audioInputUrl: './audio/stay-a-while.mp3', audioInputVolume: 0.5, midiInputId: 'all', isCompiling: false, compileError: null, messages: [], isAiThinking: false };
      set((state) => ({ sessions: [...state.sessions, newSession], activeSessionId: id }));
    },

    switchSession: (id) => {
      const state = get();
      const currentSession = state.getActiveSession();
      const nextSession = state.sessions.find(s => s.id === id);
      if (currentSession?.dspNode) currentSession.dspNode.disconnect();
      if (nextSession?.dspNode && state.isAudioRunning) nextSession.dspNode.connect(state.getAudioCtx().destination);
      set({ activeSessionId: id });
    },

    deleteSession: (id) => {
      set((state) => {
        const session = state.sessions.find(s => s.id === id);
        if (session?.dspNode) { session.dspNode.disconnect(); session.dspNode.destroy(); }
        const newSessions = state.sessions.filter(s => s.id !== id);
        let nextId = state.activeSessionId;
        if (id === state.activeSessionId) nextId = newSessions.length > 0 ? newSessions[0].id : '';
        return { sessions: newSessions, activeSessionId: nextId };
      });
    },

    renameSession: (id, name) => set((state) => ({ sessions: state.sessions.map((s) => s.id === id ? { ...s, name } : s) })),
    updateActiveSession: (updates) => set((state) => ({ sessions: state.sessions.map((s) => s.id === state.activeSessionId ? { ...s, ...updates } : s) })),
    updateSession: (id, updates) => set((state) => ({ sessions: state.sessions.map((s) => s.id === id ? { ...s, ...updates } : s) })),
    getActiveSession: () => { const state = get(); return state.sessions.find(s => s.id === state.activeSessionId); },

    setSettings: async (settings) => {
      const current = get();
      const newProvider = settings.provider || current.provider;
      const newApiKeys = { ...current.apiKeys };
      
      if (settings.apiKey !== undefined) {
        newApiKeys[newProvider] = settings.apiKey;
        if (isElectron) {
          const encrypted = await (window as any).ipcRenderer.invoke('safe-storage:encrypt', settings.apiKey);
          safeLocalStorage.setItem(`faust_api_key_secure_${newProvider}`, encrypted);
          safeLocalStorage.removeItem(`faust_api_key_${newProvider}`);
        } else {
          safeLocalStorage.setItem(`faust_api_key_${newProvider}`, settings.apiKey);
        }
      }

      let newModel = settings.model !== undefined ? settings.model : current.model;
      let newModels = settings.models || current.models;

      if (settings.provider && settings.provider !== current.provider) {
        newModels = []; 
        const newApiKey = newApiKeys[newProvider];
        const savedModel = safeLocalStorage.getItem(`faust_model_${newProvider}`);
        
        if (!newApiKey) {
          newModel = '';
        } else if (savedModel) {
          newModel = savedModel;
        } else {
          switch(newProvider) {
            case 'moonshot': newModel = 'moonshot-v1-8k'; break;
            case 'gemini': newModel = 'gemini-1.5-flash-latest'; break;
            case 'deepseek': newModel = 'deepseek-chat'; break;
            case 'glm': newModel = 'glm-4'; break;
          }
        }
      }

      // Final safety check: if no key for the active provider, force clear model
      if (!newApiKeys[newProvider]) {
        newModel = '';
        newModels = [];
      }

      safeLocalStorage.setItem('faust_provider', newProvider);
      if (newModel) {
        safeLocalStorage.setItem(`faust_model_${newProvider}`, newModel);
      } else {
        safeLocalStorage.removeItem(`faust_model_${newProvider}`);
      }

      set({ provider: newProvider, apiKeys: newApiKeys, model: newModel, customBaseUrl: settings.customBaseUrl ?? current.customBaseUrl, models: newModels });
    },

    setAudioRunning: (running) => set({ isAudioRunning: running }),
    setInitialized: (initialized) => set({ isInitialized: initialized }),
    setMidiDevices: (midiDevices) => set({ midiDevices }),
    setLastMidiNote: (lastMidiNote) => set({ lastMidiNote }),
    getAudioCtx: () => {
      if (!globalAudioCtx) globalAudioCtx = new (window.AudioContext || (window as any).webkitAudioContext)();
      return globalAudioCtx;
    }
  };
});
