name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: macos-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Web Assets
        run: npm run build

      - name: Package Electron App (macOS & Windows)
        run: npx electron-builder --mac --win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        with:
          files: |
            release/*.zip
            release/*.dmg
            release/*.exe
          generate_release_notes: true

      - name: Deploy to Vercel (Production)
        uses: amondnet/vercel-action@v25
        if: startsWith(github.ref, 'refs/tags/')
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod'